from ._generator_ import admin_field_generator
from .general import general
from .date import date
from .datetime import datetime
from .timedelta import timedelta
from .template import template
from .url import url
from .image import image
from .number import number
from .currency import currency
from .table import table
